//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TextChat_P2P_GUI.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_TEXTCHATP2PGUI_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_TEXTCHATP2PGUI			107
#define IDI_SMALL				108
#define IDC_TEXTCHATP2PGUI			109
//my tag
#define IDC_EDIT_TEXT	110
#define IDC_BUTTON_CALL	111
#define IDC_LIST_CLIENT 112
#define IDC_EDIT_TEXT_STATIC 113
#define IDC_EDIT_TEXT_CHAT_STATIC 114
#define IDC_EDIT_TEXT_CHAT 115
#define IDC_BUTTON_SEND 116
#define IDC_EDIT_TEXT_STATIC_LOGIN 117
#define IDC_EDIT_TEXT_USER 118
#define IDC_EDIT_TEXT_PASSWORD 119
#define IDC_BUTTON_LOGIN 120
#define IDC_EDIT_TEXT_STATIC_MSG 121
#define IDC_EDIT_TEXT_STATIC_CALL_FROM 122
#define IDC_EDIT_TEXT_STATIC_CALLER_NAME 123
#define IDC_BUTTON_ACCEPT 124
#define IDC_BUTTON_DECLINE 125
#define IDC_EDIT_TEXT_STATIC_IN_THE_CALL 126
#define IDC_EDIT_TEXT_STATIC__IN_THE_CALL_CALLER_NAME 127
#define IDC_BUTTON_STOP 128
#define IDC_EDIT_TEXT_CHAT_STATIC_IN_THE_CALL_CHAT 129
#define IDC_EDIT_TEXT_CHAT_IN_THE_CALL 130
#define IDC_BUTTON_SEND_IN_THE_CALL 131
//my tag
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
